---
- name: Update yum
  yum: name=* state=latest

- name: Generate test template
  template:
    src: test_template.j2
    dest: /tmp/test_file

- debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
